name: brick_build_test_example
description: Testing the code generation library and interface for Brick components
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_build_test
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  brick_build_test:
    path: ../
