name: brick
repository: https://github.com/GetDutchie/brick

packages:
  - packages/*

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true

    changelogs:

  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true
