name: brick_offline_first_with_rest
description: A Brick domain that routes data fetching through local providers
  before a REST providers.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_rest
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 3.3.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  brick_core: ^1.3.0
  brick_offline_first: ">=3.0.0 <4.0.0"
  brick_rest: ">=3.0.3 <4.0.0"
  brick_sqlite: ">=3.0.0 <4.0.0"
  collection: ">=1.15.0 <2.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  http: ">=1.0.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  path: ^1.8.0
  sqflite_common: ">=2.0.0 <3.0.0"

dev_dependencies:
  lints:
  mockito:
  sqflite_common_ffi:
  test:
