name: brick_offline_first_with_rest
description: A Brick domain that routes data fetching through local providers
  before a REST providers.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_rest
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  brick_core: ^1.0.0+1
  brick_offline_first: ^2.0.0-rc.2
  brick_offline_first_with_rest_abstract: ^0.0.2
  brick_offline_first_abstract: ^2.0.0-rc.2
  brick_rest: ^1.1.0
  brick_sqlite: ^1.1.0
  brick_sqlite_abstract: ^1.0.0+3
  collection: ^1.15.0
  dart_style: ^2.0.0
  http: ^0.13.0
  logging: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  sqflite: ^2.0.0+1

dev_dependencies:
  mockito: ^5.0.0
  test: ^1.16.5
  sqflite_common: ^2.0.0+1
  sqflite_common_ffi: ^2.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
