// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250620024829_up = [
  InsertTable('Financing'),
  InsertTable('Branch'),
  InsertTable('TransactionItem'),
  InsertTable('Customer'),
  InsertTable('Pizza'),
  InsertTable('FinanceProvider'),
  InsertTable('Inventory'),
  InsertColumn('id', Column.varchar, onTable: 'Financing', unique: true),
  InsertColumn('requested', Column.boolean, onTable: 'Financing'),
  InsertColumn('status', Column.varchar, onTable: 'Financing'),
  InsertForeignKey('Financing', 'FinanceProvider', foreignKeyColumn: 'provider_FinanceProvider_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('finance_provider_id', Column.varchar, onTable: 'Financing'),
  InsertColumn('amount', Column.num, onTable: 'Financing'),
  InsertColumn('approval_date', Column.datetime, onTable: 'Financing'),
  InsertColumn('id', Column.varchar, onTable: 'Branch', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Branch'),
  InsertColumn('server_id', Column.integer, onTable: 'Branch'),
  InsertColumn('location', Column.varchar, onTable: 'Branch'),
  InsertColumn('description', Column.varchar, onTable: 'Branch'),
  InsertColumn('active', Column.boolean, onTable: 'Branch'),
  InsertColumn('business_id', Column.integer, onTable: 'Branch'),
  InsertColumn('latitude', Column.varchar, onTable: 'Branch'),
  InsertColumn('longitude', Column.varchar, onTable: 'Branch'),
  InsertColumn('is_default', Column.boolean, onTable: 'Branch'),
  InsertColumn('is_online', Column.boolean, onTable: 'Branch'),
  InsertColumn('id', Column.varchar, onTable: 'TransactionItem', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('quantity_requested', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('quantity_approved', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('quantity_shipped', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('transaction_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('variant_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('qty', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('price', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('discount', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('remaining_stock', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('created_at', Column.datetime, onTable: 'TransactionItem'),
  InsertColumn('updated_at', Column.datetime, onTable: 'TransactionItem'),
  InsertColumn('is_refunded', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('done_with_transaction', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('active', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('dc_rt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('dc_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('taxbl_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('tax_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('tot_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('item_seq', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('isrcc_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('isrcc_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('isrc_rt', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('isrc_amt', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('tax_ty_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('bcd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_cls_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_ty_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_std_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('orgn_nat_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('pkg', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('pkg_unit_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('qty_unit_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('prc', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('sply_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('tin', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('dft_prc', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('add_info', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('isrc_aplcb_yn', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('use_yn', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('regr_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('regr_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('modr_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('modr_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('last_touched', Column.datetime, onTable: 'TransactionItem'),
  InsertColumn('branch_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('part_of_composite', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('composite_price', Column.Double, onTable: 'TransactionItem'),
  InsertForeignKey('TransactionItem', 'Inventory', foreignKeyColumn: 'inventory_request_Inventory_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('inventory_request_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('ignore_for_report', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('id', Column.varchar, onTable: 'Customer', unique: true),
  InsertColumn('first_name', Column.varchar, onTable: 'Customer'),
  InsertColumn('last_name', Column.varchar, onTable: 'Customer'),
  InsertColumn('id', Column.varchar, onTable: 'Pizza', unique: true),
  InsertColumn('frozen', Column.boolean, onTable: 'Pizza'),
  InsertForeignKey('Pizza', 'Customer', foreignKeyColumn: 'customer_Customer_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'FinanceProvider', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'FinanceProvider'),
  InsertColumn('interest_rate', Column.num, onTable: 'FinanceProvider'),
  InsertColumn('suppliers_that_accept_this_finance_facility', Column.varchar, onTable: 'FinanceProvider'),
  InsertColumn('id', Column.varchar, onTable: 'Inventory', unique: true),
  InsertColumn('main_branch_id', Column.integer, onTable: 'Inventory'),
  InsertColumn('sub_branch_id', Column.integer, onTable: 'Inventory'),
  InsertColumn('created_at', Column.datetime, onTable: 'Inventory'),
  InsertColumn('status', Column.varchar, onTable: 'Inventory'),
  InsertColumn('delivery_date', Column.datetime, onTable: 'Inventory'),
  InsertColumn('delivery_note', Column.varchar, onTable: 'Inventory'),
  InsertColumn('order_note', Column.varchar, onTable: 'Inventory'),
  InsertColumn('customer_received_order', Column.boolean, onTable: 'Inventory'),
  InsertColumn('driver_request_delivery_confirmation', Column.boolean, onTable: 'Inventory'),
  InsertColumn('driver_id', Column.integer, onTable: 'Inventory'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Inventory'),
  InsertColumn('item_counts', Column.num, onTable: 'Inventory'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Inventory'),
  InsertColumn('tin_number', Column.varchar, onTable: 'Inventory'),
  InsertForeignKey('Inventory', 'Financing', foreignKeyColumn: 'financing_Financing_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('financing_id', Column.varchar, onTable: 'Inventory'),
  InsertForeignKey('Inventory', 'Branch', foreignKeyColumn: 'branch_Branch_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('branch_id', Column.varchar, onTable: 'Inventory'),
  CreateIndex(columns: ['id'], onTable: 'Financing', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Branch', unique: true),
  CreateIndex(columns: ['id'], onTable: 'TransactionItem', unique: true),
  CreateIndex(columns: ['transaction_id'], onTable: 'TransactionItem', unique: false),
  CreateIndex(columns: ['variant_id'], onTable: 'TransactionItem', unique: false),
  CreateIndex(columns: ['id'], onTable: 'FinanceProvider', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Inventory', unique: true)
];

const List<MigrationCommand> _migration_20250620024829_down = [
  DropTable('Financing'),
  DropTable('Branch'),
  DropTable('TransactionItem'),
  DropTable('Customer'),
  DropTable('Pizza'),
  DropTable('FinanceProvider'),
  DropTable('Inventory'),
  DropColumn('id', onTable: 'Financing'),
  DropColumn('requested', onTable: 'Financing'),
  DropColumn('status', onTable: 'Financing'),
  DropColumn('provider_FinanceProvider_brick_id', onTable: 'Financing'),
  DropColumn('finance_provider_id', onTable: 'Financing'),
  DropColumn('amount', onTable: 'Financing'),
  DropColumn('approval_date', onTable: 'Financing'),
  DropColumn('id', onTable: 'Branch'),
  DropColumn('name', onTable: 'Branch'),
  DropColumn('server_id', onTable: 'Branch'),
  DropColumn('location', onTable: 'Branch'),
  DropColumn('description', onTable: 'Branch'),
  DropColumn('active', onTable: 'Branch'),
  DropColumn('business_id', onTable: 'Branch'),
  DropColumn('latitude', onTable: 'Branch'),
  DropColumn('longitude', onTable: 'Branch'),
  DropColumn('is_default', onTable: 'Branch'),
  DropColumn('is_online', onTable: 'Branch'),
  DropColumn('id', onTable: 'TransactionItem'),
  DropColumn('name', onTable: 'TransactionItem'),
  DropColumn('quantity_requested', onTable: 'TransactionItem'),
  DropColumn('quantity_approved', onTable: 'TransactionItem'),
  DropColumn('quantity_shipped', onTable: 'TransactionItem'),
  DropColumn('transaction_id', onTable: 'TransactionItem'),
  DropColumn('variant_id', onTable: 'TransactionItem'),
  DropColumn('qty', onTable: 'TransactionItem'),
  DropColumn('price', onTable: 'TransactionItem'),
  DropColumn('discount', onTable: 'TransactionItem'),
  DropColumn('remaining_stock', onTable: 'TransactionItem'),
  DropColumn('created_at', onTable: 'TransactionItem'),
  DropColumn('updated_at', onTable: 'TransactionItem'),
  DropColumn('is_refunded', onTable: 'TransactionItem'),
  DropColumn('done_with_transaction', onTable: 'TransactionItem'),
  DropColumn('active', onTable: 'TransactionItem'),
  DropColumn('dc_rt', onTable: 'TransactionItem'),
  DropColumn('dc_amt', onTable: 'TransactionItem'),
  DropColumn('taxbl_amt', onTable: 'TransactionItem'),
  DropColumn('tax_amt', onTable: 'TransactionItem'),
  DropColumn('tot_amt', onTable: 'TransactionItem'),
  DropColumn('item_seq', onTable: 'TransactionItem'),
  DropColumn('isrcc_cd', onTable: 'TransactionItem'),
  DropColumn('isrcc_nm', onTable: 'TransactionItem'),
  DropColumn('isrc_rt', onTable: 'TransactionItem'),
  DropColumn('isrc_amt', onTable: 'TransactionItem'),
  DropColumn('tax_ty_cd', onTable: 'TransactionItem'),
  DropColumn('bcd', onTable: 'TransactionItem'),
  DropColumn('item_cls_cd', onTable: 'TransactionItem'),
  DropColumn('item_ty_cd', onTable: 'TransactionItem'),
  DropColumn('item_std_nm', onTable: 'TransactionItem'),
  DropColumn('orgn_nat_cd', onTable: 'TransactionItem'),
  DropColumn('pkg', onTable: 'TransactionItem'),
  DropColumn('item_cd', onTable: 'TransactionItem'),
  DropColumn('pkg_unit_cd', onTable: 'TransactionItem'),
  DropColumn('qty_unit_cd', onTable: 'TransactionItem'),
  DropColumn('item_nm', onTable: 'TransactionItem'),
  DropColumn('prc', onTable: 'TransactionItem'),
  DropColumn('sply_amt', onTable: 'TransactionItem'),
  DropColumn('tin', onTable: 'TransactionItem'),
  DropColumn('bhf_id', onTable: 'TransactionItem'),
  DropColumn('dft_prc', onTable: 'TransactionItem'),
  DropColumn('add_info', onTable: 'TransactionItem'),
  DropColumn('isrc_aplcb_yn', onTable: 'TransactionItem'),
  DropColumn('use_yn', onTable: 'TransactionItem'),
  DropColumn('regr_id', onTable: 'TransactionItem'),
  DropColumn('regr_nm', onTable: 'TransactionItem'),
  DropColumn('modr_id', onTable: 'TransactionItem'),
  DropColumn('modr_nm', onTable: 'TransactionItem'),
  DropColumn('last_touched', onTable: 'TransactionItem'),
  DropColumn('branch_id', onTable: 'TransactionItem'),
  DropColumn('ebm_synced', onTable: 'TransactionItem'),
  DropColumn('part_of_composite', onTable: 'TransactionItem'),
  DropColumn('composite_price', onTable: 'TransactionItem'),
  DropColumn('inventory_request_Inventory_brick_id', onTable: 'TransactionItem'),
  DropColumn('inventory_request_id', onTable: 'TransactionItem'),
  DropColumn('ignore_for_report', onTable: 'TransactionItem'),
  DropColumn('id', onTable: 'Customer'),
  DropColumn('first_name', onTable: 'Customer'),
  DropColumn('last_name', onTable: 'Customer'),
  DropColumn('id', onTable: 'Pizza'),
  DropColumn('frozen', onTable: 'Pizza'),
  DropColumn('customer_Customer_brick_id', onTable: 'Pizza'),
  DropColumn('id', onTable: 'FinanceProvider'),
  DropColumn('name', onTable: 'FinanceProvider'),
  DropColumn('interest_rate', onTable: 'FinanceProvider'),
  DropColumn('suppliers_that_accept_this_finance_facility', onTable: 'FinanceProvider'),
  DropColumn('id', onTable: 'Inventory'),
  DropColumn('main_branch_id', onTable: 'Inventory'),
  DropColumn('sub_branch_id', onTable: 'Inventory'),
  DropColumn('created_at', onTable: 'Inventory'),
  DropColumn('status', onTable: 'Inventory'),
  DropColumn('delivery_date', onTable: 'Inventory'),
  DropColumn('delivery_note', onTable: 'Inventory'),
  DropColumn('order_note', onTable: 'Inventory'),
  DropColumn('customer_received_order', onTable: 'Inventory'),
  DropColumn('driver_request_delivery_confirmation', onTable: 'Inventory'),
  DropColumn('driver_id', onTable: 'Inventory'),
  DropColumn('updated_at', onTable: 'Inventory'),
  DropColumn('item_counts', onTable: 'Inventory'),
  DropColumn('bhf_id', onTable: 'Inventory'),
  DropColumn('tin_number', onTable: 'Inventory'),
  DropColumn('financing_Financing_brick_id', onTable: 'Inventory'),
  DropColumn('financing_id', onTable: 'Inventory'),
  DropColumn('branch_Branch_brick_id', onTable: 'Inventory'),
  DropColumn('branch_id', onTable: 'Inventory'),
  DropIndex('index_Financing_on_id'),
  DropIndex('index_Branch_on_id'),
  DropIndex('index_TransactionItem_on_id'),
  DropIndex('index_TransactionItem_on_transaction_id'),
  DropIndex('index_TransactionItem_on_variant_id'),
  DropIndex('index_FinanceProvider_on_id'),
  DropIndex('index_Inventory_on_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250620024829',
  up: _migration_20250620024829_up,
  down: _migration_20250620024829_down,
)
class Migration20250620024829 extends Migration {
  const Migration20250620024829()
    : super(
        version: 20250620024829,
        up: _migration_20250620024829_up,
        down: _migration_20250620024829_down,
      );
}
