// GENERATED CODE DO NOT EDIT
// This file should be version controlled
import 'package:brick_sqlite/db.dart';
part '20250620024829.migration.dart';

/// All intelligently-generated migrations from all `@Migratable` classes on disk
final migrations = <Migration>{
  const Migration20250620024829(),};

/// A consumable database structure including the latest generated migration.
final schema = Schema(
  0,
  generatorVersion: 1,
  tables: <SchemaTable>{
    SchemaTable(
      'Financing',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('requested', Column.boolean),
        SchemaColumn('status', Column.varchar),
        SchemaColumn(
          'provider_FinanceProvider_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'FinanceProvider',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('finance_provider_id', Column.varchar),
        SchemaColumn('amount', Column.num),
        SchemaColumn('approval_date', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Branch',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('server_id', Column.integer),
        SchemaColumn('location', Column.varchar),
        SchemaColumn('description', Column.varchar),
        SchemaColumn('active', Column.boolean),
        SchemaColumn('business_id', Column.integer),
        SchemaColumn('latitude', Column.varchar),
        SchemaColumn('longitude', Column.varchar),
        SchemaColumn('is_default', Column.boolean),
        SchemaColumn('is_online', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'TransactionItem',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('quantity_requested', Column.integer),
        SchemaColumn('quantity_approved', Column.integer),
        SchemaColumn('quantity_shipped', Column.integer),
        SchemaColumn('transaction_id', Column.varchar),
        SchemaColumn('variant_id', Column.varchar),
        SchemaColumn('qty', Column.Double),
        SchemaColumn('price', Column.Double),
        SchemaColumn('discount', Column.Double),
        SchemaColumn('remaining_stock', Column.Double),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('is_refunded', Column.boolean),
        SchemaColumn('done_with_transaction', Column.boolean),
        SchemaColumn('active', Column.boolean),
        SchemaColumn('dc_rt', Column.Double),
        SchemaColumn('dc_amt', Column.Double),
        SchemaColumn('taxbl_amt', Column.Double),
        SchemaColumn('tax_amt', Column.Double),
        SchemaColumn('tot_amt', Column.Double),
        SchemaColumn('item_seq', Column.integer),
        SchemaColumn('isrcc_cd', Column.varchar),
        SchemaColumn('isrcc_nm', Column.varchar),
        SchemaColumn('isrc_rt', Column.integer),
        SchemaColumn('isrc_amt', Column.integer),
        SchemaColumn('tax_ty_cd', Column.varchar),
        SchemaColumn('bcd', Column.varchar),
        SchemaColumn('item_cls_cd', Column.varchar),
        SchemaColumn('item_ty_cd', Column.varchar),
        SchemaColumn('item_std_nm', Column.varchar),
        SchemaColumn('orgn_nat_cd', Column.varchar),
        SchemaColumn('pkg', Column.varchar),
        SchemaColumn('item_cd', Column.varchar),
        SchemaColumn('pkg_unit_cd', Column.varchar),
        SchemaColumn('qty_unit_cd', Column.varchar),
        SchemaColumn('item_nm', Column.varchar),
        SchemaColumn('prc', Column.Double),
        SchemaColumn('sply_amt', Column.Double),
        SchemaColumn('tin', Column.integer),
        SchemaColumn('bhf_id', Column.varchar),
        SchemaColumn('dft_prc', Column.Double),
        SchemaColumn('add_info', Column.varchar),
        SchemaColumn('isrc_aplcb_yn', Column.varchar),
        SchemaColumn('use_yn', Column.varchar),
        SchemaColumn('regr_id', Column.varchar),
        SchemaColumn('regr_nm', Column.varchar),
        SchemaColumn('modr_id', Column.varchar),
        SchemaColumn('modr_nm', Column.varchar),
        SchemaColumn('last_touched', Column.datetime),
        SchemaColumn('branch_id', Column.varchar),
        SchemaColumn('ebm_synced', Column.boolean),
        SchemaColumn('part_of_composite', Column.boolean),
        SchemaColumn('composite_price', Column.Double),
        SchemaColumn(
          'inventory_request_Inventory_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Inventory',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('inventory_request_id', Column.varchar),
        SchemaColumn('ignore_for_report', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
        SchemaIndex(columns: ['transaction_id'], unique: false),
        SchemaIndex(columns: ['variant_id'], unique: false),
      },
    ),
    SchemaTable(
      'Customer',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('first_name', Column.varchar),
        SchemaColumn('last_name', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Pizza',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('frozen', Column.boolean),
        SchemaColumn(
          'customer_Customer_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Customer',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'FinanceProvider',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('interest_rate', Column.num),
        SchemaColumn(
          'suppliers_that_accept_this_finance_facility',
          Column.varchar,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Inventory',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('main_branch_id', Column.integer),
        SchemaColumn('sub_branch_id', Column.integer),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('delivery_date', Column.datetime),
        SchemaColumn('delivery_note', Column.varchar),
        SchemaColumn('order_note', Column.varchar),
        SchemaColumn('customer_received_order', Column.boolean),
        SchemaColumn('driver_request_delivery_confirmation', Column.boolean),
        SchemaColumn('driver_id', Column.integer),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('item_counts', Column.num),
        SchemaColumn('bhf_id', Column.varchar),
        SchemaColumn('tin_number', Column.varchar),
        SchemaColumn(
          'financing_Financing_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Financing',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('financing_id', Column.varchar),
        SchemaColumn(
          'branch_Branch_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Branch',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('branch_id', Column.varchar),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
  },
);
