name: brick_rest_example

version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brick_rest:
    path: ../

dependency_overrides:
  brick_core:
    path: ../../brick_core
