name: brick_build_example

publish_to: none

version: 0.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brick_build:
    path: ../

dependency_overrides:
  brick_core:
    path: ../../brick_core
