name: brick_offline_first_with_rest_abstract
description: Annotations and models required by the Offline First with Rest domain.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_abstract_with_rest
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  brick_core: ^1.0.0+1
  brick_offline_first_abstract: ^2.0.0
  brick_rest: ^1.0.0+3
  brick_sqlite_abstract: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
