name: brick_supabase_abstract
description: Supabase annotations and model/adapter to remove the Flutter restriction on build packages
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_supabase_abstract
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  brick_core: ^1.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.5
