name: brick_offline_first_with_graphql_abstract_example

publish_to: none

version: 0.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  brick_offline_first_with_graphql_abstract:
    path: ../
