name: pizza_shoppe
description: A new Flutter project.

version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: any

dev_dependencies:
  brick_offline_first_with_rest_build:
    path: ../packages/brick_offline_first_with_rest_build
  build_runner: any
  shelf: ^1.1.0

flutter:
  uses-material-design: true
