# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  brickSchemaBuilder:
    import: "package:brick_offline_first_with_rest_build/builder.dart"
    builder_factories: ["offlineFirstSchemaBuilder"]
    build_extensions: {".brick_aggregate.dart": [".brick_aggregate.schema_build_offline_first.dart"]}
    build_to: cache
    auto_apply: root_package
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["brickNewMigrationBuilder"]
  brickAggregateBuilder:
    import: "package:brick_offline_first_with_rest_build/builder.dart"
    builder_factories: ["offlineFirstAggregateBuilder"]
    build_extensions: {"$lib$": ["models_and_migrations.brick_aggregate.dart"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["brickSchemaBuilder"]
    auto_apply: root_package
    defaults:
      generate_for:
        exclude:
          - lib/app/adapters/*.dart
          - app/adapters/*.dart
          - lib/app/db/*.dart
          - app/db/*.dart
  brickAdaptersBuilder:
    import: "package:brick_offline_first_with_rest_build/builder.dart"
    builder_factories: ["offlineFirstAdaptersBuilder"]
    build_extensions: {".dart": [".adapter_build_offline_first.dart"]}
    build_to: cache
    auto_apply: root_package
    applies_builders: ["source_gen|combining_builder"]
    defaults:
      generate_for:
        include:
          - lib/app/models/*.dart
          - app/models/*.dart
        exclude:
          - lib/app/adapters/*.dart
          - app/adapters/*.dart
          - lib/app/db/*.dart
          - app/db/*.dart
  brickNewMigrationBuilder:
    import: "package:brick_offline_first_with_rest_build/builder.dart"
    builder_factories: ["offlineFirstNewMigrationBuilder"]
    build_extensions: {".brick_aggregate.dart": [".brick_aggregate.migration_build_offline_first.dart"]}
    build_to: cache
    auto_apply: root_package
  brickModelDictionaryBuilder:
    import: "package:brick_offline_first_with_rest_build/builder.dart"
    builder_factories: ["offlineFirstModelDictionaryBuilder"]
    build_extensions: {".brick_aggregate.dart": [".brick_aggregate.model_dictionary_build_offline_first.dart"]}
    build_to: cache
    auto_apply: root_package
    applies_builders: ["source_gen|combining_builder"]
