name: Brick Offline First
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/brick_offline_first/**"
      - ".github/workflows/brick_offline_first.yaml"

defaults:
  run:
    shell: bash

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analyze_test:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:${{ matrix.flutter_version }}
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [dev, stable]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@89f242ee29e10c53a841bfe71cc0ce7b2f065abc
        with:
          access_token: ${{ github.token }}
      - name: Install SQLite3
        run: sudo apt-get update && sudo apt-get -y install sqlite3 libsqlite3-dev
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: ${{ runner.os }}-brick_offline_first-v1-${{ matrix.flutter_version }}-${{ hashFiles('packages/brick_offline_first/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-brick_offline_first-v1-${{ matrix.flutter_version }}
      - id: checkout
        uses: actions/checkout@v2.3.4

      - run: flutter pub get
        working-directory: packages/brick_offline_first

      - run: dart analyze --fatal-infos lib
        working-directory: packages/brick_offline_first

      - run: dart format --output=none --line-length 100 --set-exit-if-changed lib
        working-directory: packages/brick_offline_first

      - run: flutter test
        working-directory: packages/brick_offline_first
