name: Brick Core
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/brick_core/**"
      - ".github/workflows/brick_core.yaml"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analyze_format_test:
    uses: GetDutchie/brick/.github/workflows/reusable-dart-analyze-format-test.yaml@main
    with:
      package: brick_core
