name: Brick Offline First
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/brick_offline_first/**"
      - ".github/workflows/brick_offline_first.yaml"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analyze_format_test:
    uses: ./.github/workflows/reusable-dart-analyze-format-test.yaml
    with:
      package: brick_offline_first
