name: Brick Offline First with GraphQL Abstract
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/brick_offline_first_with_graphql_abstract/**"
      - ".github/workflows/brick_offline_first_with_graphql_abstract.yaml"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analyze_format_test:
    uses: GetDutchie/brick/.github/workflows/reusable-dart-analyze-format-test.yaml@main
    with:
      package: brick_offline_first_with_graphql_abstract
