name: Brick JSON Generators
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/brick_json_generators/**"
      - ".github/workflows/brick_json_generators.yaml"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analyze_format_test:
    uses: ./.github/workflows/reusable-dart-analyze-format-test.yaml
    with:
      package: brick_json_generators
