name: brick_realm
description: Realm Connector for Brick, a persistence layer for Flutter. Realm is a mobile database - an alternative to SQLite and key-value stores.
homepage: https://github.com/MarcusSorealheis/brick/tree/main/packages/brick_realm
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/realm/realm-dart/issues

version: 0.8.0+rc

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.0
  build_cli_annotations: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.0
  ffi: ^2.0.1
  json_annotation: ^4.7.0
  logging: ^1.0.0
  meta: ^1.1.8
  package_config: ^2.0.0
  path: ^1.0.0
  pubspec_parse: ^1.0.0
  pub_semver: ^2.1.0
  realm_common:
    path: ./common
  realm_generator:
    path: ./generator
  tar: ^0.5.4
  build_runner: ^2.1.0
  http: ^0.13.4
  cancellation_token: ^1.5.0

dev_dependencies:
  build_cli: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.14.3
  timezone: ^0.9.0

platforms:
  windows:
  linux:
  macos:
